services:
  - type: web
    name: valuefy-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python start.py
    envVars:
      - key: OPENAI_API_KEY
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: MYSQL_URI
        sync: false
      - key: VERCEL_DOMAIN
        sync: false
      - key: PYTHON_VERSION
        value: "3.11"
